name: Integration Test

on:
  workflow_dispatch:
    inputs:
      jimm-version:
        description: >
          JIMM version tag to use. This will decide the version of JIMM to start e.g. v3.1.7.
          View all available versions at https://github.com/canonical/jimm/pkgs/container/jimm.
        required: true
  pull_request:
  merge_group:

jobs:
  startjimm:
    name: Test JIMM with Juju controller
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout JIMM repo
        uses: actions/checkout@v4

      - name: Setup Go
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Go vendor to speed up docker build
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        run: go mod vendor

      - name: Start JIMM (pull request)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        uses: ./.github/actions/test-server
        with:
          jimm-version: dev
          juju-channel: "3/stable"
          ghcr-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Start JIMM (manual run)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/test-server
        with:
          jimm-version: ${{ inputs.jimm-version }}
          juju-channel: "3/stable"
          ghcr-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a model, deploy an application and run juju status
        run: |
          juju add-model foo && \
          juju deploy haproxy && \
          sleep 5 && \
          juju status
